# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: xiaomu's blog
subtitle: 小木de

# subtitle_desc: "无关风月，随便写写...."

description: "任何事情都会有皆大欢喜的结果，如果没有，那就证明没有到最后..."
keywords: "前端开发、全栈工程师"
author: 小木
language: zh-CN
# timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Search 
search:
  path: search.xml
  field: post
  content: true
  format: html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 12
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next7

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:real-jacket/real-jacket.github.io.git


# # 一下是hexo-them-skapp 配置

# # Site
# # 博客的标题
# # title: MINFIVE

# # banner显示的子标题
# # subtitle: MINFIVE BLOG

# # banner显示的简短介绍
# # subtitle_desc: 日常学习与兴趣交流

# # seo关键字
# # keywords: minfive, minfive blog, 前端博客, 前端, 程序员, 前端开发, 全栈开发, node.js, javascript

# # 博客介绍（同时用于seo）
# # description: 日常学习与兴趣交流的个人博客

# # 个人介绍
# # introduction: 不思量，自难忘！

# # 博客的favicon图标，支持本地及在线两种方式，本地请将图标放置于 themes/hexo-theme-skapp/source/img 目录下
# favicon_ico: http://oo12ugek5.bkt.clouddn.com/blog/images/favicon.ico

# # 博客的左上角logo图标，支持本地及在线两种方式
# logo: http://oo12ugek5.bkt.clouddn.com/images/logo-text-white.png

# # 头像/二维码（用于显示在底部）二选一
# avatar: http://oo12ugek5.bkt.clouddn.com/images/qrcode.png
# # qrcode: http://oo12ugek5.bkt.clouddn.com/images/qrcode.png

# # 文章的默认封面
# default_cover: http://oo12ugek5.bkt.clouddn.com/images/default_cover.png

# # header 的背景图
# header_cover: http://oo12ugek5.bkt.clouddn.com/blog/images/banner-bg.jpg

# # 404 页面的背景图
# error_page_bg: http://oo12ugek5.bkt.clouddn.com/blog/images/dogs.jpg

# # 页面加载loading图标
# loader_img: http://oo12ugek5.bkt.clouddn.com/blog/images/loader.gif

# # 站长信息
# # author:
# #   name: minfive
# #   link: https://github.com/Mrminfive
# # 用于页面 footer 的站长信息
# about:
#   info: 本站是基于 Hexo 搭建的静态资源博客，主要用于分享日常学习、生活及工作的一些心得总结，欢迎点击右下角订阅 rss。
#   address: Guangzhou, Guangdong Province, China
#   email: chenxiaowu1994@outlook.com

# menu:
#   home: / 
#   archive: /archives
#   search: /search
#   works: /works
#   about: /about